In [ ]:
!pip install ampligraph

     |████████████████████████████████| 168 kB 5.1 MB/s 
     |████████████████████████████████| 6.4 MB 53.1 MB/s 
     |████████████████████████████████| 2.7 MB 46.0 MB/s 
     |████████████████████████████████| 407 kB 57.9 MB/s 
     |████████████████████████████████| 64 kB 2.3 MB/s 
     |████████████████████████████████| 120 kB 62.6 MB/s 
     |████████████████████████████████| 561 kB 49.5 MB/s 
     |████████████████████████████████| 69 kB 7.1 MB/s 
     |████████████████████████████████| 42 kB 797 kB/s 
     |████████████████████████████████| 45 kB 3.0 MB/s 
     |████████████████████████████████| 90 kB 8.6 MB/s 
     |████████████████████████████████| 121 kB 45.0 MB/s 
     |████████████████████████████████| 100 kB 8.0 MB/s 
     |████████████████████████████████| 84 kB 2.6 MB/s 
  Created wheel for commonmark: filename=CommonMark-0.5.4-py3-none-any.whl size=30766 sha256=4a0b2748f3c5046af373fcfcde56b17b056eeea82d8b121da169b65fb8189b92
  Stored in directory: /root/.cache/pip/whee

In [ ]:
!pip install "tensorflow-gpu>=1.15.2,<2.0"

     |████████████████████████████████| 411.0 MB 25 kB/s 
     |████████████████████████████████| 503 kB 64.3 MB/s 
     |████████████████████████████████| 3.8 MB 31.2 MB/s 
     |████████████████████████████████| 20.1 MB 1.4 MB/s 
     |████████████████████████████████| 2.9 MB 45.0 MB/s 
     |████████████████████████████████| 50 kB 5.1 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=10ca0857bad0e56342eae1b984f8737e94b00f954e8f08e7862f0f573e4b45bb
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.2.0
    Uninstalling importlib-metadata-4.2.0:
      Successfully uninstalled importlib-metadata-4.2.0
  Attempting uninstall: h5p

In [1]:
import numpy as np
from ampligraph.latent_features import ComplEx

model = ComplEx(batches_count=1, seed=555, epochs=20, k=10)
X = np.array([['a', 'y', 'b'],
              ['b', 'y', 'a'],
              ['a', 'y', 'c'],
              ['c', 'y', 'a'],
              ['a', 'y', 'd'],
              ['c', 'y', 'd'],
              ['b', 'y', 'c'],
              ['f', 'y', 'e']])
model.fit(X)
model.get_embeddings(['f','e'], embedding_type='entity')

WARNING - All triples will be processed in the same batch (batches_count=1). When processing large graphs it is recommended to batch the input knowledge graph instead.


array([[ 0.25670585, -0.3011869 , -0.23950092,  0.14284079,  0.32528725,
        -0.17080608,  0.34406787, -0.20753211,  0.07970539, -0.22319023,
         0.15641478,  0.30420542,  0.36425987, -0.22927509, -0.2680887 ,
        -0.47432607,  0.0217801 , -0.5583782 , -0.4031471 ,  0.108514  ],
       [-0.15706335,  0.27334124, -0.4666501 , -0.34397012,  0.11477758,
         0.17332976,  0.35828054,  0.0821802 ,  0.43514463, -0.23554587,
        -0.0664973 , -0.13745542,  0.05554105, -0.45979163, -0.03638605,
        -0.44420683,  0.08366295, -0.07778159, -0.3768378 , -0.00928266]],
      dtype=float32)

In [2]:
model.get_embeddings(['a'], embedding_type='entity')

array([[-0.10371958, -0.14583218,  0.22096074, -0.6052284 ,  0.05482241,
        -0.0196579 ,  0.25527224,  0.24141456, -0.04165557,  0.28237548,
        -0.29211932, -0.35728115, -0.27753964,  0.21847081, -0.10824742,
        -0.04499299, -0.13122639,  0.30512977,  0.2142967 ,  0.25706917]],
      dtype=float32)

In [11]:
model.get_embeddings(['f'], embedding_type='entity')

array([[ 0.25670585, -0.3011869 , -0.23950092,  0.14284079,  0.32528725,
        -0.17080608,  0.34406787, -0.20753211,  0.07970539, -0.22319023,
         0.15641478,  0.30420542,  0.36425987, -0.22927509, -0.2680887 ,
        -0.47432607,  0.0217801 , -0.5583782 , -0.4031471 ,  0.108514  ]],
      dtype=float32)

In [12]:
model.get_embeddings(['y'], embedding_type='relation')

array([[-1.7087938e-01,  1.4999509e-01,  2.9407182e-01,  1.8625981e-01,
        -1.6001947e-01,  4.9188279e-04, -1.9712371e-01,  5.2929765e-01,
        -3.3518019e-01, -4.5672062e-01,  5.0781357e-01,  1.9965298e-01,
        -3.9932293e-01, -2.7712131e-01, -2.2794114e-01,  2.9238033e-01,
        -2.1377882e-01,  5.2952880e-01, -4.7254694e-01,  3.2151541e-01]],
      dtype=float32)

In [13]:
!pip install adjustText

  Created wheel for adjustText: filename=adjustText-0.7.3-py3-none-any.whl size=7094 sha256=552cfd58e1a519534b66be69c2a3fe8f2a5ca031147ac2e8a27f774908a0c78a
  Stored in directory: /root/.cache/pip/wheels/2f/98/32/afbf902d8f040fadfdf0a44357e4ab750afe165d873bf5893d
Successfully built adjustText


In [14]:
!git clone  https://github.com/wyldebeast-wunderliebe/incf.countryutils.git

Cloning into 'incf.countryutils'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 124 (delta 15), reused 33 (delta 14), pack-reused 87
Receiving objects: 100% (124/124), 65.24 KiB | 3.26 MiB/s, done.
Resolving deltas: 100% (53/53), done.


In [15]:
!cd incf.countryutils

In [16]:
!pwd

/content


In [17]:
!pip install ./incf.countryutils/


Processing ./incf.countryutils
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Created wheel for incf.countryutils2: filename=incf.countryutils2-1.2-py3-none-any.whl size=26074 sha256=aff537e9959c6db5e7f63a4e43e49414f5804e6c754dba5698067fda6233b65c
  Stored in directory: /tmp/pip-ephem-wheel-cache-5n6ywa19/wheels/28/df/14/2ca2edf3870fd95994ba18ebe635600b9b522e626ef2dc357f
Successfully built incf.countryutils2


In [21]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [31]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Korean_RE/data/results/news_domain_kg.csv')
df

삼성전자                    다음_국가의_것임      인도
0        삼성전자                    다음_국가의_것임      중국
1        삼성전자                    해당_개체의_제품    스마트폰
2          인도                          수교국      중국
3          인도                    해당_개체의_제품    스마트폰
4          중국                          수교국      인도
...       ...                          ...     ...
42000     유동근                 해당_개체의_친형제자매     김상중
42001     유동근                   해당_개체의_배우자     서이숙
42002      꼬리              해당_개체가_다음의_일부분임    더 뱅커
42003     말기암                        하위_개념  항암바이러스
42004  항암바이러스  다음과_다르지만_같은_의미인_것처럼_혼동되는_항목     말기암

[42005 rows x 3 columns]

In [32]:
X = load_from_csv('.', 'football.csv', sep=',')[:, 1:]
print(X)

[['TeamScotland' 'isHomeTeam' 'Match0']
 ['TeamEngland' 'isAwayTeam' 'Match0']
 ['TeamScotland' 'draws' 'Match0']
 ...
 ['Match40770' 'atYear' '2019']
 ['Match40770' 'homeScores' '1']
 ['Match40770' 'awayScores' '0']]


In [35]:
X = load_from_csv('.', '/content/drive/MyDrive/Korean_RE/data/results/news_domain_kg.csv', sep=',')
print(X)

[['삼성전자' '다음_국가의_것임' '인도']
 ['삼성전자' '다음_국가의_것임' '중국']
 ['삼성전자' '해당_개체의_제품' '스마트폰']
 ...
 ['꼬리' '해당_개체가_다음의_일부분임' '더 뱅커']
 ['말기암' '하위_개념' '항암바이러스']
 ['항암바이러스' '다음과_다르지만_같은_의미인_것처럼_혼동되는_항목' '말기암']]


In [36]:
import numpy as np
import pandas as pd
import requests

from ampligraph.datasets import load_from_csv
from ampligraph.latent_features import ComplEx
from ampligraph.evaluation import evaluate_performance
from ampligraph.evaluation import mr_score, mrr_score, hits_at_n_score
from ampligraph.evaluation import train_test_split_no_unseen

# International football matches triples
# url = 'https://ampligraph.s3-eu-west-1.amazonaws.com/datasets/football.csv'
# open('football.csv', 'wb').write(requests.get(url).content)
# X = load_from_csv('.', 'football.csv', sep=',')[:, 1:]

# triple_csv = '/content/drive/MyDrive/Korean_RE/data/results/news_domain_kg.csv'
X = load_from_csv('/content/drive/MyDrive/Korean_RE/data/results/', 'news_domain_kg.csv', sep=',')

# Train test split
X_train, X_test = train_test_split_no_unseen(X, test_size=1000)

# ComplEx model
model = ComplEx(batches_count=50,
                epochs=300,
                k=100,
                eta=20,
                optimizer='adam',
                optimizer_params={'lr':1e-4},
                loss='multiclass_nll',
                regularizer='LP',
                regularizer_params={'p':3, 'lambda':1e-5},
                seed=0,
                verbose=True)

model.fit(X_train)

Average ComplEx Loss:   0.027516: 100%|██████████| 300/300 [22:24<00:00,  4.48s/epoch]


In [40]:
# model.get_embeddings(['f','e'], embedding_type='entity')
model.get_embeddings(['삼성전자'], embedding_type='entity').shape

(1, 200)

In [41]:
model.get_embeddings(['손흥민'], embedding_type='entity')

array([[ 0.29380497,  0.15711589,  0.20047657, -0.02385921, -0.134398  ,
         0.23113863, -0.18074143, -0.3326762 , -0.3149612 ,  0.2256267 ,
        -0.01953783, -0.09940026, -0.4234142 ,  0.02212378,  0.2736314 ,
         0.4607077 , -0.42999572, -0.23379624,  0.3148194 ,  0.3197042 ,
        -0.45867008,  0.33704543, -0.19676608, -0.20914422,  0.09739388,
         0.28271648,  0.04154048,  0.37051898,  0.27658722,  0.26245582,
         0.20153579, -0.377528  , -0.03205306,  0.3112742 ,  0.02034313,
        -0.27937406, -0.30875117,  0.24753074,  0.10131042,  0.13021734,
         0.04230977,  0.2084685 , -0.24125679, -0.39078543, -0.05844074,
         0.27152   ,  0.21487595,  0.3158436 ,  0.28755322, -0.27715328,
        -0.1986003 , -0.14543106,  0.07685877, -0.30324534,  0.00099276,
         0.3275533 ,  0.16988838, -0.17343076, -0.05999562,  0.18949877,
         0.41446182,  0.04433723, -0.0135366 , -0.02399682, -0.10335149,
        -0.285254  , -0.26895136, -0.05351179, -0.2

In [42]:
model.get_embeddings(['해당_개체의_제조사'], embedding_type='relation')

array([[ 9.8150361e-01,  3.7045199e-01, -1.0737088e+00,  5.9603043e-02,
         1.1122440e+00,  8.6190826e-01,  1.0918491e+00,  8.9380944e-01,
        -1.0915350e+00,  8.8850343e-01, -6.0184622e-01, -8.8777554e-01,
        -6.4362156e-01, -2.6129195e-01, -7.5193065e-01,  1.0881727e+00,
         5.0997585e-01, -9.9358267e-01,  1.0995481e+00, -1.0923445e+00,
         4.6208331e-01,  1.0168653e+00,  1.1714410e+00,  1.1561873e+00,
        -8.9681588e-02,  9.9386507e-01,  1.1443816e+00,  5.7711023e-01,
         3.3828795e-01,  1.1269757e+00,  4.5743212e-01, -7.3614407e-01,
         9.1771317e-01,  1.2259729e+00,  8.8158369e-01, -6.9460815e-01,
         9.9154747e-01, -7.5661647e-01,  1.0420854e-01, -7.8168583e-01,
         7.2174197e-01,  8.4355766e-01,  8.6005324e-01,  1.0557370e+00,
         1.2097059e+00, -8.6890697e-01,  1.0071330e+00, -8.7902835e-03,
         7.9273266e-01, -8.5127270e-01, -5.8961540e-02,  9.0930718e-01,
        -9.8536134e-01, -6.5162009e-01,  1.0018477e+00, -1.00597

In [47]:
y_pred = model.predict(np.array([['인공지능', '해당_개체의_제조사', '삼성전자']]))
y_pred

array([13.040573], dtype=float32)

In [48]:
y_pred = model.predict(np.array([['인공지능', '해당_개체의_제품', '삼성전자']]))
y_pred

array([-1.7425735], dtype=float32)

In [49]:
y_pred = model.predict(np.array([['인공지능', '다음과_다르지만_같은_의미인_것처럼_혼동되는_항목', '로봇']]))
y_pred

array([4.870197], dtype=float32)

In [51]:
from ampligraph.utils import save_model, restore_model

model_name = "/content/drive/MyDrive/Korean_RE/kge/news_domain_kg_embedding.pkl"

save_model(model, model_name_path=model_name)

In [52]:
restored_model = restore_model(model_name_path=model_name)

# use the restored model
y_pred = restored_model.predict(np.array([['인공지능', '해당_개체의_제조사', '삼성전자']]))
y_pred

array([13.040573], dtype=float32)

In [60]:
restored_model.get_embeddings(['인공지능'], embedding_type='entity')

array([[ 0.46595478, -0.30585882,  0.29781452, -0.0501992 ,  0.0162836 ,
        -0.27524713, -0.00770139, -0.3451445 , -0.49774048,  0.40234452,
         0.04948333,  0.3772119 ,  0.4334331 , -0.20175157, -0.04376844,
        -0.31181392,  0.06022745,  0.1509922 , -0.40094823,  0.176837  ,
         0.06775962, -0.31940502, -0.18472143,  0.28550097,  0.3138354 ,
         0.33115828,  0.07491156,  0.14671896, -0.06969238,  0.4762035 ,
        -0.27749342,  0.3550516 ,  0.15766574,  0.08499383,  0.0045298 ,
         0.33258665, -0.45567054,  0.12875533,  0.14740399, -0.17375585,
         0.2532541 ,  0.22957942, -0.48467872,  0.13883258, -0.35932183,
         0.05857145, -0.41023692, -0.20576799, -0.41630659,  0.25333038,
         0.31234124,  0.31385607, -0.56067634,  0.36201766, -0.15480259,
        -0.49626788, -0.27809113, -0.19660963, -0.17744592, -0.0057651 ,
        -0.32905585,  0.15791489,  0.29121038, -0.20053592, -0.06681545,
         0.48515868,  0.26968905,  0.30619103, -0.3

In [61]:
model.get_embeddings(['인공지능'], embedding_type='entity')

array([[ 0.46595478, -0.30585882,  0.29781452, -0.0501992 ,  0.0162836 ,
        -0.27524713, -0.00770139, -0.3451445 , -0.49774048,  0.40234452,
         0.04948333,  0.3772119 ,  0.4334331 , -0.20175157, -0.04376844,
        -0.31181392,  0.06022745,  0.1509922 , -0.40094823,  0.176837  ,
         0.06775962, -0.31940502, -0.18472143,  0.28550097,  0.3138354 ,
         0.33115828,  0.07491156,  0.14671896, -0.06969238,  0.4762035 ,
        -0.27749342,  0.3550516 ,  0.15766574,  0.08499383,  0.0045298 ,
         0.33258665, -0.45567054,  0.12875533,  0.14740399, -0.17375585,
         0.2532541 ,  0.22957942, -0.48467872,  0.13883258, -0.35932183,
         0.05857145, -0.41023692, -0.20576799, -0.41630659,  0.25333038,
         0.31234124,  0.31385607, -0.56067634,  0.36201766, -0.15480259,
        -0.49626788, -0.27809113, -0.19660963, -0.17744592, -0.0057651 ,
        -0.32905585,  0.15791489,  0.29121038, -0.20053592, -0.06681545,
         0.48515868,  0.26968905,  0.30619103, -0.3